language: cpp



script:
  - sudo apt-get update -qq
  - sudo apt-get install -y ia32-libs libc6-i386 libc6-dev-i386 lib32gcc1 lib32stdc++6
  - bash build.sh

notifications:
  irc: "foco.ca.irc.tl#sa-mp+"
  on_failure: always
  on_success: change