language: cpp



script:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-4.8-multilib
  - bash build.sh

notifications:
  irc: "foco.ca.irc.tl#sa-mp+"
  on_failure: always
  on_success: change