language: cpp



script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6-dev-i386
  - sudo ln -s /usr/lib32/libstdc++.so.6 /usr/lib32/libstdc++.so
  - bash build.sh

notifications:
  irc: "foco.ca.irc.tl#sa-mp+"
  on_failure: always
  on_success: change